import 'package:do_an_ltdd/models/product_model.dart';
import 'package:flutter/material.dart';

class ProductDetail {

  final String CPU, RAM, OCung, CardDoHoa, ManHinh, CongGiaoTiep, Audio, BanPhim, ChuanLan, ChuanWifi, Bluetooth, WebCam, HeDieuHanh, Pin, TrongLuong, MauSac, KichThuoc;
  final int id, idctsp;
  ProductDetail({
    required this.id,
    required this.idctsp,
    required this.CPU,
    required this.RAM,
    required this.OCung,
    required this.CardDoHoa,
    required this.ManHinh,
    required this.CongGiaoTiep,

    required this.Audio,
    required this.BanPhim,
  
    required this.ChuanLan,
    required this.ChuanWifi,
    required this.Bluetooth,
    required this.WebCam,
    required this.HeDieuHanh,
    required this.Pin,
    required this.TrongLuong,
    required this.MauSac,
    required this.KichThuoc
  });
}
final List<ProductDetail> productdetails = [
  ProductDetail(
      id: 1,
      idctsp: 1,
      CPU: "Intel® Core™ i5-11400H Processor 2.7 GHz",
      RAM: "8GB DDR4 3200MHz", 
      OCung: "512GB SSD M.2 PCIE G3X2, 1x slot M.2",
      CardDoHoa: "NVIDIA® GeForce RTX™ 3050 Laptop GPU + Intel® UHD Graphics",
      ManHinh: "15.6-inch FHD",
      CongGiaoTiep: "1x RJ45 LAN port \n1x USB Type C \n3x USB 3.2 Gen 1 Type-A \n1x 3.5mm Combo Audio Jack \n1x HDMI",
      Audio: "DTS:X® Ultra",
      BanPhim: "1-Zone RGB",
      ChuanLan: "10/100/1000/Gigabits Base T",
      ChuanWifi: "802.11AC (2X2)",
      Bluetooth: "BT 5.0",
      WebCam: "HD 720p",
      HeDieuHanh: "Windows 11 Home",
      Pin: "3 Cell 41WWHr",
      TrongLuong: "2.3 kg",
      MauSac: "Gun Metal",
      KichThuoc: "35.9 x 25.6 x 2.28 ~ 2.43 cm",
  ),
  ProductDetail(
      id: 2,
      idctsp: 2,
      CPU: "Intel® Core™ i5-11400H Processor 2.7 GHz",
      RAM: "8GB DDR4 3200MHz", 
      OCung: "512GB SSD M.2 PCIE G3X2, 1x slot M.2",
      CardDoHoa: "NVIDIA® GeForce RTX™ 3050 Laptop GPU + Intel® UHD Graphics",
      ManHinh: "15.6-inch FHD",
      CongGiaoTiep: "1x RJ45 LAN port \n1x USB Type C \n3x USB 3.2 Gen 1 Type-A \n1x 3.5mm Combo Audio Jack \n1x HDMI",
      Audio: "DTS:X® Ultra",
      BanPhim: "1-Zone RGB",
      ChuanLan: "10/100/1000/Gigabits Base T",
      ChuanWifi: "802.11AC (2X2)",
      Bluetooth: "BT 5.0",
      WebCam: "HD 720p",
      HeDieuHanh: "Windows 11 Home",
      Pin: "3 Cell 41WWHr",
      TrongLuong: "2.3 kg",
      MauSac: "Gun Metal",
      KichThuoc: "35.9 x 25.6 x 2.28 ~ 2.43 cm",
  ),
  ProductDetail(
      id: 3,
      idctsp: 3,
      CPU: "Intel® Core™ i5-11400H Processor 2.7 GHz",
      RAM: "8GB DDR4 3200MHz", 
      OCung: "512GB SSD M.2 PCIE G3X2, 1x slot M.2",
      CardDoHoa: "NVIDIA® GeForce RTX™ 3050 Laptop GPU + Intel® UHD Graphics",
      ManHinh: "15.6-inch FHD",
      CongGiaoTiep: "1x RJ45 LAN port \n1x USB Type C \n3x USB 3.2 Gen 1 Type-A \n1x 3.5mm Combo Audio Jack \n1x HDMI",
      Audio: "DTS:X® Ultra",
      BanPhim: "1-Zone RGB",
      ChuanLan: "10/100/1000/Gigabits Base T",
      ChuanWifi: "802.11AC (2X2)",
      Bluetooth: "BT 5.0",
      WebCam: "HD 720p",
      HeDieuHanh: "Windows 11 Home",
      Pin: "3 Cell 41WWHr",
      TrongLuong: "2.3 kg",
      MauSac: "Gun Metal",
      KichThuoc: "35.9 x 25.6 x 2.28 ~ 2.43 cm",
  ),
  ProductDetail(
      id: 4,
      idctsp: 4,
      CPU: "Intel® Core™ i5-11400H Processor 2.7 GHz",
      RAM: "8GB DDR4 3200MHz", 
      OCung: "512GB SSD M.2 PCIE G3X2, 1x slot M.2",
      CardDoHoa: "NVIDIA® GeForce RTX™ 3050 Laptop GPU + Intel® UHD Graphics",
      ManHinh: "15.6-inch FHD",
      CongGiaoTiep: "1x RJ45 LAN port \n1x USB Type C \n3x USB 3.2 Gen 1 Type-A \n1x 3.5mm Combo Audio Jack \n1x HDMI",
      Audio: "DTS:X® Ultra",
      BanPhim: "1-Zone RGB",
      ChuanLan: "10/100/1000/Gigabits Base T",
      ChuanWifi: "802.11AC (2X2)",
      Bluetooth: "BT 5.0",
      WebCam: "HD 720p",
      HeDieuHanh: "Windows 11 Home",
      Pin: "3 Cell 41WWHr",
      TrongLuong: "2.3 kg",
      MauSac: "Gun Metal",
      KichThuoc: "35.9 x 25.6 x 2.28 ~ 2.43 cm",
  ),
  ProductDetail(
      id: 5,
      idctsp: 5,
      CPU: "Intel® Core™ i5-11400H Processor 2.7 GHz",
      RAM: "8GB DDR4 3200MHz", 
      OCung: "512GB SSD M.2 PCIE G3X2, 1x slot M.2",
      CardDoHoa: "NVIDIA® GeForce RTX™ 3050 Laptop GPU + Intel® UHD Graphics",
      ManHinh: "15.6-inch FHD",
      CongGiaoTiep: "1x RJ45 LAN port \n1x USB Type C \n3x USB 3.2 Gen 1 Type-A \n1x 3.5mm Combo Audio Jack \n1x HDMI",
      Audio: "DTS:X® Ultra",
      BanPhim: "1-Zone RGB",
      ChuanLan: "10/100/1000/Gigabits Base T",
      ChuanWifi: "802.11AC (2X2)",
      Bluetooth: "BT 5.0",
      WebCam: "HD 720p",
      HeDieuHanh: "Windows 11 Home",
      Pin: "3 Cell 41WWHr",
      TrongLuong: "2.3 kg",
      MauSac: "Gun Metal",
      KichThuoc: "35.9 x 25.6 x 2.28 ~ 2.43 cm",
  ),
];